const img = (id) =>
  `https://images.unsplash.com/photo-${id}?w=600&q=80&auto=format&fit=crop`;

export const dummyProducts = [
  {
    _id: '1',
    name: 'Royal Beard Elixir',
    slug: 'royal-beard-elixir',
    description: 'Luxury beard oil infused with argan, jojoba, and sandalwood.',
    category: 'beard',
    images: [img('1616390323981-fd529c7d7f9a')],
    price: 899,
    comparePrice: 1199,
    stock: 120,
    isFeatured: true,
    isTrending: true,
    ratings: 4.8,
    numReviews: 234,
    ingredients: ['Argan Oil', 'Jojoba', 'Sandalwood'],
    usageGuide: 'Apply 4-6 drops to damp beard.',
  },
  {
    _id: '2',
    name: 'Midnight Beard Balm',
    slug: 'midnight-beard-balm',
    description: 'Matte-hold balm with beeswax and shea butter.',
    category: 'beard',
    images: [img('1622286342628-267fd0f9389f')],
    price: 749,
    comparePrice: 999,
    stock: 85,
    isTrending: true,
    ratings: 4.6,
    numReviews: 156,
  },
  {
    _id: '3',
    name: 'Charcoal Detox Face Wash',
    slug: 'charcoal-detox-face-wash',
    description: 'Deep-cleansing activated charcoal wash.',
    category: 'face',
    images: [img('1556228720-195a672ede8b')],
    price: 599,
    comparePrice: 799,
    stock: 200,
    isFeatured: true,
    isTrending: true,
    ratings: 4.7,
    numReviews: 412,
  },
  {
    _id: '4',
    name: 'Hydra Shield Moisturizer',
    slug: 'hydra-shield-moisturizer',
    description: '24hr hydration gel-cream with hyaluronic acid.',
    category: 'face',
    images: [img('1570172619644-dfd03ed5d874')],
    price: 849,
    comparePrice: 1099,
    stock: 150,
    isFeatured: true,
    ratings: 4.9,
    numReviews: 289,
  },
  {
    _id: '5',
    name: 'Titanium Hair Wax',
    slug: 'titanium-hair-wax',
    description: 'High-hold, zero-flake wax with metallic finish.',
    category: 'hair',
    images: [img('1522338241087-90e20e0ad128')],
    price: 649,
    comparePrice: 849,
    stock: 175,
    isTrending: true,
    ratings: 4.5,
    numReviews: 198,
  },
  {
    _id: '6',
    name: 'Neon Volume Pomade',
    slug: 'neon-volume-pomade',
    description: 'Medium shine pomade for voluminous styles.',
    category: 'hair',
    images: [img('1608248548313-54348c404a40')],
    price: 699,
    comparePrice: 899,
    stock: 90,
    ratings: 4.4,
    numReviews: 87,
  },
  {
    _id: '7',
    name: 'Cyber King Grooming Kit',
    slug: 'cyber-king-grooming-kit',
    description: 'Complete grooming arsenal bundle.',
    category: 'bundle',
    isBundle: true,
    bundleSavePercent: 25,
    images: [img('1599351431202-1e0c2647b7ca')],
    price: 2499,
    comparePrice: 3345,
    stock: 50,
    isFeatured: true,
    ratings: 4.9,
    numReviews: 67,
  },
  {
    _id: '8',
    name: 'Alpha Beard Duo',
    slug: 'alpha-beard-duo',
    description: 'Beard oil + balm combo pack.',
    category: 'bundle',
    isBundle: true,
    bundleSavePercent: 18,
    images: [img('1621605815971-fbc98d665033')],
    price: 1299,
    comparePrice: 1648,
    stock: 75,
    isTrending: true,
    ratings: 4.8,
    numReviews: 45,
  },
];

export const dummyBlogs = [
  {
    _id: 'b1',
    title: "The Modern Desi Man's Grooming Ritual",
    slug: 'modern-desi-grooming-ritual',
    excerpt: 'Discover the 5-step routine that transforms your daily grind.',
    coverImage: img('1616390323981-fd529c7d7f9a'),
    readTime: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'b2',
    title: 'Beard Care 101: From Patchy to Powerful',
    slug: 'beard-care-101',
    excerpt: 'Science-backed tips to grow and style your beard.',
    coverImage: img('1621605815971-fbc98d665033'),
    readTime: 8,
    createdAt: new Date().toISOString(),
  },
];

export const testimonials = [
  {
    name: 'Arjun Mehta',
    role: 'Entrepreneur, Mumbai',
    text: 'Desii Gabru changed my morning routine. The beard elixir is pure luxury.',
    rating: 5,
  },
  {
    name: 'Vikram Singh',
    role: 'Creative Director',
    text: 'Cyber luxury aesthetic meets real results. My skin has never looked better.',
    rating: 5,
  },
  {
    name: 'Rohan Kapoor',
    role: 'Fitness Coach',
    text: 'The Titanium Wax holds through workouts. Zero compromise on style.',
    rating: 5,
  },
];

export const faqs = [
  {
    q: 'Are Desii Gabru products cruelty-free?',
    a: 'Yes. All products are cruelty-free and formulated without parabens or sulfates.',
  },
  {
    q: 'How long does shipping take?',
    a: 'Orders ship within 24-48 hours. Delivery takes 3-7 business days across India.',
  },
  {
    q: 'What is your return policy?',
    a: 'Unopened products can be returned within 14 days for a full refund.',
  },
  {
    q: 'Do you offer international shipping?',
    a: 'Currently we ship across India. International shipping coming soon.',
  },
];
